int comparar (char * cpCad1, char* cpCad2);
int compararU (unsigned char * cpCad1, unsigned char* cpCad2);
void concatenar (char * cpCad1, char* cpCad2);
void concatenarU (unsigned char * cpCad1, unsigned char* cpCad2);
void copiar(char * cpCad1, char* cpCad2);
void copiarU(unsigned char * cpCad1, unsigned char* cpCad2);
int longitudCadena(char* cpCad);
int longitudCadenaU(unsigned char* ucpCad);
void miitoa (char cadenaDestino[], long lNumero);
int miatoi (char* cadena);
void reemplazar (char* cpCadena, char cCaracterBuscado, char cCaracterDeReemplazo);
int contarDigitos (long numero);
int incluido (unsigned char* ucpCadena, unsigned char* ucpCadenaABuscar);
void miitoa2 (unsigned char *, long);
