#ifndef _ESTRUCTURAS_H
#define _ESTRUCTURAS_H


/* Estados del ARRAY para los servicios */

#define ESTADO_INICIALIZADO_SINCRONIZADO		100
#define ESTADO_INICIALIZADO_SINCRONIZANDO		101
#define ESTADO_FUERASERVICIO_INCOMPLETO		102
#define ESTADO_FUERASERVICIO_SINCRONIZADO		103
#define ESTADO_FUERASERVICIO_CORRUPTO		104
#define ESTADO_FUERASERVICIO			105
#define ESTADO_FUNCIONAL				106

/* CONSTANTES HANDSHAKE */
#define HANDSHAKE_DISCO				0x91 /* Actualizado */
#define HANDSHAKE_ARRAY				0x91 /* Actualizado */
#define HANDSHAKE_VSK 				0x91 /* Actualizado */
#define HANDSHAKE_OK					0x98 /* Actualizado */
#define HANDSHAKE_FAIL				0x99 /* Actualizado */

/* Constantes de PROTOCOLO */
#define IPCIRC_PUT_SECTORES				0x08
#define IPCIRC_PUT_SECTORES_OK			0x74
#define IPCIRC_GET_SECTORES				0x07
#define IPCIRC_GET_SECTORES2			0x11
#define IPCIRC_GET_SECTORES1			0x12
#define IPCIRC_GET_SECTORES_RTAb		0x72
#define IPCIRC_GET_SECTORES_RTA			0x73
#define IPCIRC_GET_CHS					0x14
#define IPCIRC_GET_CHS_RTA				0x75


#define IPCIRC_NUEVO_ARRAY				0x70
#define IPCIRC_FUERA_SERVICIO			0x97
#define IPCIRC_HILO_DESCONECTAR			0x80
#define IPCIRC_CONSOLA				0x81
#define IPCIRC_CONSOLA_AGREDARDA			0x82
#define IPCIRC_CONSOLA_ELIMINARDA			0x83
#define IPCIRC_CONSOLA_INICIARSERVICIO		0x84
#define IPCIRC_CONSOLA_FUERASERVICIO		0x85
#define IPCIRC_CONSOLA_ESTADO			0x86
#define IPCIRC_FINALIZAR_SISTEMA			0x87

#define IPCIRC_HILO					0x60

/* Constantes de retorno de la funcion del HILO */
#define HILO_DESCONEXION				200
#define HILO_CONEXION_PADRE_FAIL			201

#define IPCIRC_FALLA					0x97
#define FALLA_SISTEMA				-999


#endif
